---
- hosts: manager
  roles:
  - role: mrlesmithjr.netplan
    become: yes
    netplan_enabled: true
    netplan_configuration:
      network:
         version: 2
         ethernets:
            ens192:
              dhcp4: no
              gateway4: "{{ mygw }}"
              addresses:
              - "{{ myaddr }}"
              nameservers:
                search:
                - "{{ myaddomain }}"
                addresses:
                - "{{ mydc }}"
  - role: geerlingguy.ntp
    become: yes
    ntp_manage_config: true
    ntp_tinker_panic: true
    ntp_timezone: "{{ mytimezone }}"
    ntp_servers:
    - "{{ mydc }}"

- hosts: manager
  tasks:
  - name: install pexpect
    become: yes
    package:
      state: present
      name:
      - python3-pexpect
   
- hosts: manager
  roles:
  - role: thulium_drake.adjoin
    become: yes
    adjoin_domains:
      - { name: "{{ myaddomain }}",
          workgroup: "{{ myadwindomain }}",
          domain_controllers: [
            "{{ mydc }}"
          ],
          ldap_base_dn: "{{ myadbasedn }}",
          computer_objects_path: 'Computers',
          linuxadmins: 'linuxadmins',
          username: "{{ myaduser }}",
          password: "{{ myadpass }}"
        }
