---
- hosts: localhost
  gather_facts: false
  tasks:
  - name: create Datacenter
    delegate_to: localhost
    vmware_datacenter:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      datacenter_name: "{{ myvmdcname }}"
      validate_certs: false
      state: present
  - name: create Cluster
    delegate_to: localhost
    vmware_cluster:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      datacenter_name: "{{ myvmdcname }}"
      cluster_name: "{{ myvmclname }}"
      validate_certs: false
      state: present
  - name: Add ESXi Host 1 to vCenter
    delegate_to: localhost
    vmware_host:
      hostname: '{{ vcenter_hostname }}'
      username: '{{ vcenter_username }}'
      password: '{{ vcenter_password }}'
      datacenter: "{{ myvmdcname }}"
      cluster: "{{ myvmclname }}"
      esxi_hostname: "esx01.fsimonetti.lan"
      esxi_username: '{{ esxi_username }}'
      esxi_password: '{{ esxi_password }}'
      validate_certs: false
      state: present
  - name: Add ESXi license to host 1
    delegate_to: localhost
    vcenter_license:
      hostname: '{{ vcenter_hostname }}'
      username: '{{ vcenter_username }}'
      password: '{{ vcenter_password }}'
      esxi_hostname: "esx01.fsimonetti.lan"
      license: '{{ esxi_license }}'
      validate_certs: false
      state: present      
  - name: Add ESXi Host 2 to vCenter
    delegate_to: localhost
    vmware_host:
      hostname: '{{ vcenter_hostname }}'
      username: '{{ vcenter_username }}'
      password: '{{ vcenter_password }}'
      datacenter: "{{ myvmdcname }}"
      cluster: "{{ myvmclname }}"
      esxi_hostname: "esx02.fsimonetti.lan"
      esxi_username: '{{ esxi_username }}'
      esxi_password: '{{ esxi_password }}'
      validate_certs: false
      state: present
  - name: Add ESXi license to host 2
    delegate_to: localhost
    vcenter_license:
      hostname: '{{ vcenter_hostname }}'
      username: '{{ vcenter_username }}'
      password: '{{ vcenter_password }}'
      esxi_hostname: "esx02.fsimonetti.lan"
      license: '{{ esxi_license }}'
      validate_certs: false
      state: present
  - name: Add vCenter license to VCSA
    delegate_to: localhost
    vcenter_license:
      hostname: '{{ vcenter_hostname }}'
      username: '{{ vcenter_username }}'
      password: '{{ vcenter_password }}'
      license: '{{ vcenter_license }}'
      validate_certs: false
      state: present
  - name: Mount NFS datastores to host 1
    delegate_to: localhost
    vmware_host_datastore:
      hostname: '{{ vcenter_hostname }}'
      username: '{{ vcenter_username }}'
      password: '{{ vcenter_password }}'
      validate_certs: false
      nfs_server: '{{ mynfs }}'
      nfs_path: '{{ item.path }}'
      datastore_type: 'nfs'
      datastore_name: '{{ item.name }}'
      esxi_hostname: "esx01.fsimonetti.lan"
      state: present
      nfs_ro: no
    loop:
      - { 'name': 'iso-ds', 'path': '/mnt/cl0/v0/iso-ds'}
      - { 'name': 'vm-ds', 'path': '/mnt/cl0/v1/vm-ds'}
  - name: Mount NFS datastores to host 2
    delegate_to: localhost
    vmware_host_datastore:
      hostname: '{{ vcenter_hostname }}'
      username: '{{ vcenter_username }}'
      password: '{{ vcenter_password }}'
      validate_certs: false
      nfs_server: '{{ mynfs }}'
      nfs_path: '{{ item.path }}'
      datastore_type: 'nfs'
      datastore_name: '{{ item.name }}'
      esxi_hostname: "esx02.fsimonetti.lan"
      state: present
      nfs_ro: no
    loop:
      - { 'name': 'iso-ds', 'path': '/mnt/cl0/v0/iso-ds'}
      - { 'name': 'vm-ds', 'path': '/mnt/cl0/v1/vm-ds'}
  - name: Create directory structure for OS ISOs and vm templates
    delegate_to: localhost
    vsphere_file:
      host:     '{{ vcenter_hostname }}'
      username: '{{ vcenter_username }}'
      password: '{{ vcenter_password }}'
      validate_certs: false
      datacenter: "{{ myvmdcname }}"
      datastore: '{{ item.ds }}'
      path: '{{ item.dst }}'
      state: directory
    loop:
      - { 'ds': 'iso-ds', 'dst': '/win' }
      - { 'ds': 'iso-ds', 'dst': '/linux' }
      - { 'ds': 'vm-ds', 'dst': '/templates' }
  - name: copy Windows 2012R2 ISO to datastore
    delegate_to: localhost  
    vsphere_copy:
      hostname: '{{ vcenter_hostname }}'
      username: '{{ vcenter_username }}'
      password: '{{ vcenter_password }}'
      validate_certs: false
      src: /iso/win/2012r2.iso
      datacenter: "{{ myvmdcname }}"
      datastore: 'iso-ds'
      path: /win/2012r2.iso
  - name: copy Windows 2016 ISO to datastore
    delegate_to: localhost  
    vsphere_copy:
      hostname: '{{ vcenter_hostname }}'
      username: '{{ vcenter_username }}'
      password: '{{ vcenter_password }}'
      validate_certs: false
      src: /iso/win/2016.iso
      datacenter: "{{ myvmdcname }}"
      datastore: 'iso-ds'
      path: /win/2016.iso
  

